//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by EthcatDO.rc
//
#define IDC_MYDOBTN0                    1
#define IDC_MYDOBTN1                    2
#define IDC_MYDOBTN2                    3
#define IDC_MYDOBTN3                    4
#define IDC_MYDOBTN4                    5
#define IDC_MYDOBTN5                    6
#define IDC_MYDOBTN6                    7
#define IDC_MYDOBTN7                    8
#define IDC_MYDOBTN8                    9
#define IDC_MYDOBTN9                    10
#define IDC_MYDOBTN10                   11
#define IDC_MYDOBTN11                   12
#define IDC_MYDOBTN12                   13
#define IDC_MYDOBTN13                   14
#define IDC_MYDOBTN14                   15
#define IDC_MYDOBTN15                   16
#define IDC_MYDOBTN16                   17
#define IDC_MYDOBTN17                   18
#define IDC_MYDOBTN18                   19
#define IDC_MYDOBTN19                   20
#define IDC_MYDOBTN20                   21
#define IDC_MYDOBTN21                   22
#define IDC_MYDOBTN22                   23
#define IDC_MYDOBTN23                   24
#define IDC_MYDOBTN24                   25
#define IDC_MYDOBTN25                   26
#define IDC_MYDOBTN26                   27
#define IDC_MYDOBTN27                   28
#define IDC_MYDOBTN28                   29
#define IDC_MYDOBTN29                   30
#define IDC_MYDOBTN30                   31
#define IDC_MYDOBTN31                   32
#define IDC_MYDOBTN32                   33
#define IDC_MYDOBTN33                   34
#define IDC_MYDOBTN34                   35
#define IDC_MYDOBTN35                   36
#define IDC_MYDOBTN36                   37
#define IDC_MYDOBTN37                   38
#define IDC_MYDOBTN38                   39
#define IDC_MYDOBTN39                   40
#define IDC_MYDOBTN40                   41
#define IDC_MYDOBTN41                   42
#define IDC_MYDOBTN42                   43
#define IDC_MYDOBTN43                   44
#define IDC_MYDOBTN44                   45
#define IDC_MYDOBTN45                   46
#define IDC_MYDOBTN46                   47
#define IDC_MYDOBTN47                   48
#define IDC_MYDOBTN48                   49
#define IDC_MYDOBTN49                   50
#define IDC_MYDOBTN50                   51
#define IDC_MYDOBTN51                   52
#define IDC_MYDOBTN52                   53
#define IDC_MYDOBTN53                   54
#define IDC_MYDOBTN54                   55
#define IDC_MYDOBTN55                   56
#define IDC_MYDOBTN56                   57
#define IDC_MYDOBTN57                   58
#define IDC_MYDOBTN58                   59
#define IDC_MYDOBTN59                   60
#define IDC_MYDOBTN60                   61
#define IDC_MYDOBTN61                   62
#define IDC_MYDOBTN62                   63
#define IDC_MYDOBTN63                   64
#define IDC_MYDOBTN64                   65
#define IDC_MYDOBTN65                   66
#define IDC_MYDOBTN66                   67
#define IDC_MYDOBTN67                   68
#define IDC_MYDOBTN68                   69
#define IDC_MYDOBTN69                   70
#define IDC_MYDOBTN70                   71
#define IDC_MYDOBTN71                   72
#define IDC_MYDOBTN72                   73
#define IDC_MYDOBTN73                   74
#define IDC_MYDOBTN74                   75
#define IDC_MYDOBTN75                   76
#define IDC_MYDOBTN76                   77
#define IDC_MYDOBTN77                   78
#define IDC_MYDOBTN78                   79
#define IDC_MYDOBTN79                   80
#define IDC_MYDOBTN80                   81
#define IDC_MYDOBTN81                   82
#define IDC_MYDOBTN82                   83
#define IDC_MYDOBTN83                   84
#define IDC_MYDOBTN84                   85
#define IDC_MYDOBTN85                   86
#define IDC_MYDOBTN86                   87
#define IDC_MYDOBTN87                   88
#define IDC_MYDOBTN88                   89
#define IDC_MYDOBTN89                   90
#define IDC_MYDOBTN90                   91
#define IDC_MYDOBTN91                   92
#define IDC_MYDOBTN92                   93
#define IDC_MYDOBTN93                   94
#define IDC_MYDOBTN94                   95
#define IDC_MYDOBTN95                   96
#define IDC_MYDOBTN96                   97
#define IDC_MYDOBTN97                   98
#define IDC_MYDOBTN98                   99
#define IDC_MYDOBTN99                   100
#define IDC_MYDOBTN100                  101
#define IDC_MYDOBTN101                  102
#define IDC_MYDOBTN102                  103
#define IDC_MYDOBTN103                  104
#define IDC_MYDOBTN104                  105
#define IDC_MYDOBTN105                  106
#define IDC_MYDOBTN106                  107
#define IDC_MYDOBTN107                  108
#define IDC_MYDOBTN108                  109
#define IDC_MYDOBTN109                  110
#define IDC_MYDOBTN110                  111
#define IDC_MYDOBTN111                  112
#define IDC_MYDOBTN112                  113
#define IDC_MYDOBTN113                  114
#define IDC_MYDOBTN114                  115
#define IDC_MYDOBTN115                  116
#define IDC_MYDOBTN116                  117
#define IDC_MYDOBTN117                  118
#define IDC_MYDOBTN118                  119
#define IDC_MYDOBTN119                  120
#define IDC_MYDOBTN120                  121
#define IDC_MYDOBTN121                  122
#define IDC_MYDOBTN122                  123
#define IDC_MYDOBTN123                  124
#define IDC_MYDOBTN124                  125
#define IDC_MYDOBTN125                  126
#define IDC_MYDOBTN126                  127
#define IDC_MYDOBTN127                  128
#define IDC_MYDOBTN128                  129


#define IDD_DO_DIALOG                   302
#define IDD_ETHCATAO_DIALOG             303
#define IDD_ETHCATAOSETUP_DIALOG        304
#define IDD_AOTRIM_DIALOG               305
#define IDD_ETHCATAI_DIALOG             306
#define IDD_ETHCATAISETUP_DIALOG        307
#define IDD_ETHCATDI_DIALOG             308
#define IDD_ETHCATDISETUP_DIALOG        309
#define IDD_ETHCATDO_DIALOG             310
#define IDD_ETHCATDOSETUP_DIALOG        311
#define IDR_MAINFRAME                   312
#define IDR_241                         313
#define IDB_BITMAP_OFF                  314
#define IDB_BITMAP_ON                   315
#define IDB_BITMAP_RED                  316
#define IDB_BITMAP_GRED                 317

#define IDC_MYEDITDO0                   500
#define IDC_MYEDITDO1                   501
#define IDC_MYEDITDO2                   502
#define IDC_MYEDITDO3                   503
#define IDC_MYEDITDO4                   504
#define IDC_MYEDITDO5                   505
#define IDC_MYEDITDO6                   506
#define IDC_MYEDITDO7                   507
#define IDC_MYEDITDOHEX0                1000
#define IDC_MYEDITDOHEX1                1001
#define IDC_AVLAIBLEDEVICE              1001
#define IDC_MYEDITDOHEX2                1002
#define IDC_MYEDITDOHEX3                1003
#define IDC_COMBO_AIChannel             1003
#define IDC_MYEDITDOHEX4                1004
#define IDC_EDIT_AIData                 1004
#define IDC_MYEDITDOHEX5                1005
#define IDC_MYEDITDOHEX6                1006
#define IDC_MYEDITDOHEX7                1006
#define IDC_BUTTON2                     1006
#define IDC_Btn_OpenBoard               1006
#define IDC_BUTTON_APPLY_OUTPUT         1006
#define IDC_BUTTON_NEG_ONT              1006
#define IDC_BUTTON_ZERO_CALI            1006
#define IDC_BUTTON3                     1007
#define IDC_BtnCloseBoard               1007
#define IDC_BUTTON_TRIM_TWINTY          1007
#define IDC_BUTTON_POS_ONT              1007
#define IDC_BUTTON_SPAN_CALII           1007
#define IDC_COMBO_AICHTYPE              1008
#define IDC_COMBO_AIRANGE               1009
#define IDC_BUTTON_AISET                1010
#define IDC_EDIT_VData                  1011
#define IDC_TAB_AIO                     1014
#define IDC_LIST1                       1015
#define IDC_LIST_AO_SETUP               1015
#define IDC_LIST_AI                     1015
#define IDC_LIST_DO                     1015
#define IDC_LIST_DI_SETUP               1015
#define IDC_BUTTON1                     1016
#define IDC_BUTTON_SETUP                1016
#define IDC_BUTTON_APPLY                1016
#define IDC_BUTTON_NEG_TEN              1016
#define IDC_BUTTON_AISETUP              1016
#define IDC_BUTTON_DOSETUP              1016
#define IDC_COMBO_CHANNEL_INDEX         1017
#define IDC_COMBO_OUTPUT_RANGE          1018
#define IDC_CHECK_ALL_FOLLOW_CHO        1019
#define IDC_SLIDER_OUTPUT               1020
#define IDC_EDIT_VALUE                  1021
#define IDC_EDIT_CURRENT_VALUE          1022
#define IDC_BUTTON_TRIM_FOR             1023
#define IDC_STATIC_START_VALUE          1024
#define IDC_STATIC_ENDVALUE             1025
#define IDC_STATIC_UNIT                 1026
#define IDC_STATIC_START_VALUES         1027
#define IDC_BUTTON_BTN_POS_TEN          1028
#define IDC_COMBO_CHANINDEX             1029
#define IDC_COMBO_INPUT_RANGE           1030
#define IDC_COMBO_INTER_TIME            1031
#define IDC_CHECK_MASK                  1032
#define IDC_CHECK_ALLCHO                1033
#define IDC_CHECK_FSV                   1035
#define IDC_CHECK_ALLFOLLWCH0           1036
#define IDC_STATIC_PORT                 1037
#define IDC_STATIC_BIT                  1038
#define IDC_STATIC_FOUR                 1039
#define IDC_STATIC_THREE                1040
#define IDC_STATIC_ZERO                 1041
#define IDC_EDIT1                       1050
#define IDC_EDIT_FILER_LOW              1051
#define IDC_EDIT_FILTER_HIGH            1052
#define IDC_LIST3                       1054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
